import os
import re
import json
from dotenv import load_dotenv
from google.genai import Client

# ENVIRONMENT CONFIG
load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found in environment variables")

client = Client(api_key=GEMINI_API_KEY)

MODEL_NAME = "gemini-2.5-flash"

# GLOBAL DISCLAIMER
DISCLAIMER = (
    "This information is generated by an AI system and is provided "
    "for general informational purposes only. It does not constitute "
    "legal advice. Please consult a licensed advocate for professional "
    "legal assistance."
)

# GEMINI CORE CALL
def ask_gemini(prompt: str):

    try:

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt
        )

        if response is None:
            return None

        # Standard text response
        if hasattr(response, "text") and response.text:
            return response.text.strip()

        # fallback extraction
        if hasattr(response, "candidates"):
            return response.candidates[0].content.parts[0].text.strip()

    except Exception as e:
        print("Gemini API Error:", e)

    return None

# JSON EXTRACTION HELPER
def extract_json(text):

    if not text:
        return None

    # Remove markdown code blocks
    text = text.replace("```json", "").replace("```", "")

    match = re.search(r"\{.*\}", text, re.DOTALL)

    if not match:
        return None

    cleaned = match.group(0)

    cleaned = re.sub(r",\s*}", "}", cleaned)
    cleaned = re.sub(r",\s*]", "]", cleaned)

    try:
        return json.loads(cleaned)
    except Exception:
        return None

# CHATBOT RESPONSE GENERATOR
def generate_reply(user_message: str, history=None):

    history_text = ""

    if history:
        for msg in history[-5:]:
            role = msg.get("role")
            content = msg.get("content")
            history_text += f"{role}: {content}\n"

    prompt = f"""
You are Virtual Advocate AI, an Indian legal information assistant.

IMPORTANT RULES:

1. Respond in the SAME language as the user's message.
2. If the user sends a greeting or casual message
   (hello, hi, good morning, thank you, etc),
   reply normally in text.
3. If the user asks a legal question, respond ONLY in JSON.
4. When mentioning laws, ALWAYS include the mapping from
   IPC (Indian Penal Code) to BNS (Bharatiya Nyaya Sanhita 2023).

LEGAL RESPONSE JSON FORMAT:

{{
"summary": "",
"applicable_laws": [
    {{
        "law": "",
        "bns_equivalent": "",
        "description": ""
    }}
],
"legal_options": [],
"next_steps": []
}}

GUIDELINES FOR LAWS:

• If an offence existed in IPC, provide BOTH IPC and BNS section.
• If it exists only in BNS, provide BNS section.
• Use correct legal terminology.

Example:

{{
"law": "IPC Section 379",
"bns_equivalent": "BNS Section 303",
"description": "Punishment for theft"
}}

Conversation history:
{history_text}

User message:
{user_message}
"""

    response = ask_gemini(prompt)

    if not response:
        return {
            "type": "text",
            "content": "AI service temporarily unavailable."
        }

    parsed = extract_json(response)

    if parsed:
        parsed["note"] = DISCLAIMER
        return {
            "type": "structured",
            "content": parsed
        }

    return {
        "type": "text",
        "content": response
    }

# AI LEGAL CATEGORY CLASSIFIER
def classify_with_ai(issue_text: str):

    prompt = f"""
You are an AI system that classifies Indian legal issues.

Classify the issue into EXACTLY ONE of the following categories:

Criminal
Family
Consumer
Civil

Definitions:

Criminal:
Offences punishable under criminal law such as
murder, assault, rape, theft, fraud, cyber crime,
harassment, threats.

Family:
Disputes involving marriage, divorce, custody,
domestic violence, maintenance, family conflicts.

Consumer:
Issues related to defective products, refund problems,
service complaints, online shopping disputes.

Civil:
Property disputes, contract disputes, land ownership
issues, employment disputes, money recovery.

STRICT RULES:
Return ONLY the category name.

Issue:
{issue_text}
"""

    result = ask_gemini(prompt)

    allowed = ["Criminal", "Family", "Consumer", "Civil"]

    if result and result.strip() in allowed:
        return result.strip(), "AI-Detected"

    if result:
        for cat in allowed:
            if cat.lower() in result.lower():
                return cat, "AI-Detected"

    return "Civil", "Low"

# AI LEGAL GUIDANCE GENERATOR
def generate_ai_guidance(category: str, issue_text: str):

    prompt = f"""
Provide legal guidance for this issue.

Return JSON format:

{{
"law":"",
"advice":"",
"procedure":[],
"note":""
}}

Category: {category}
Issue: {issue_text}
"""

    response = ask_gemini(prompt)

    if not response:
        return {
            "law": "General Indian Law",
            "advice": "AI service temporarily unavailable.",
            "procedure": ["Consult a licensed advocate"],
            "note": DISCLAIMER
        }

    parsed = extract_json(response)

    if parsed:
        parsed["note"] = DISCLAIMER
        return parsed

    return {
        "law": "General Indian Law",
        "advice": response,
        "procedure": ["Consult a licensed advocate"],
        "note": DISCLAIMER
    }

# AI CASE TITLE GENERATOR
def generate_case_title(message: str):

    prompt = f"""
You are an AI assistant for an Indian legal platform.

Generate a SHORT professional case title based on the user's issue.

Rules:
- Maximum 6 words
- Professional legal style
- No punctuation
- No quotes
- Title case format

Examples:

User issue:
Someone threatened me online

Title:
Online Criminal Intimidation Case

User issue:
Received defective product from online store

Title:
Consumer Product Defect Complaint

User issue:
{message}

Return ONLY the title.
"""

    response = ask_gemini(prompt)

    if not response:
        return "Legal Consultation"

    title = response.strip()

    # Safety cleanup
    title = title.replace('"', "").replace(".", "")

    return title
